name = "jeongwonshin-memos"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

# Static assets configuration
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# R2 bucket for Next.js incremental cache
[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "jeongwonshin-memos-cache"

# Environment variables for Giscus
[vars]
NEXT_PUBLIC_GISCUS_REPO = "newgardener/newgardener.com"
NEXT_PUBLIC_GISCUS_REPO_ID = "R_kgDOQEuT6w"
NEXT_PUBLIC_GISCUS_CATEGORY = "Comments"
NEXT_PUBLIC_GISCUS_CATEGORY_ID = "DIC_kwDOQEuT684CxFOD"